name: Playwright Tests & Publish Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest playwright pytest-html
          playwright install --with-deps

      # 4️⃣ Run Playwright tests and generate HTML report
      - name: Run tests
        run: |
          mkdir -p reports
          pytest --html=reports/test_report.html --self-contained-html -v

      # 5️⃣ Upload HTML report as artifact (optional, for download)
      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: reports/test_report.html

      # 6️⃣ Deploy HTML report to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
